# Generated by Django 2.1.3 on 2018-11-04 08:27

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='payment',
            name='direction',
            field=models.TextField(choices=[('imcoming', 'incoming'), ('outgoing', 'outgoing')], default='incoming'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.TextField(editable=False, primary_key=True, serialize=False),
        ),
    ]
